### ISSUE TITLE
pgzero 1.2 doesn't seem to exist

### ISSUE THREAD

**Issue by sils** [lordmauve/murder#3]
seems latest on pypi is 1.1: https://pypi.python.org/pypi/pgzero

requirements.txt states 1.2 though and fails to install it

**Comment by sils** [comment]
you could use this `-e` syntax to reference to the head version so pip pulls pgzero from github (or so)

**Comment by lordmauve** [comment]
The version you should install is the Pyweek tarball from https://pyweek.org/e/wasabi23/. This contains the Pygame Zero distribution needed to run the game.

**Comment by sils** [comment]
Can you do something like https://github.com/datagovuk/ckanext-dgu/blob/master/pip-requirements.txt#L17 to make installing it with `pip install -r requirements.txt` work?

**Comment by lordmauve** [comment]
Closing, it exists now.
